---
- name: Create user groups
  group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ admin_users }}"

- name: Create users
  user:
    name: "{{ item.name }}"
    shell: /usr/bin/zsh
    group: "{{ item.name }}"
    groups: sudo
    password: "{{( item.name + '9032' ) | password_hash('sha512') }}"
    update_password: on_create
    state: present
  register: changed_users
  with_items: "{{ admin_users }}"

- name: Expire new user's password
  command: "chage -d 0 {{ item.item.name }}"
  with_items: "{{ changed_users.results }}"
  when: item.changed|bool

- name: Add authorized keys for users
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.pubkey }}"
    state: present
  with_items: "{{ admin_users }}"

- name: Enable byobu
  command: byobu-enable
  become: "yes"
  become_user: "{{ item.name }}"
  with_items: "{{ changed_users.results }}"
  when: item.changed|bool
  failed_when: false

- name: Setup oh-my-zsh
  shell: echo y | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: "yes"
  become_user: "{{ item.item.name }}"
  with_items: "{{ changed_users.results }}"
  when: item.changed|bool
