---
- name: Add NeoVim PPA
  apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Add Byobu PPA
  apt_repository:
    repo: ppa:byobu/ppa

- name: Add LibreOffice PPA
  apt_repository:
    repo: ppa:libreoffice/ppa
  when: desktop|bool

- name: Install additional packages
  package:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - git
      - neovim
      - zsh
      - byobu

- name: Set NeoVim as the default editor
  alternatives:
    name: editor
    path: /usr/bin/nvim

- name: Install other optional packages
  package:
    name: "{{ other_packages }}"
    state: present
    update_cache: "yes"

- name: Update all packages on first run
  apt:
    upgrade: safe
  when: hostname != ansible_hostname
  # Only run the safe upgrade on the first run of this script.
