---
- name: Update APT package cache
  apt:
    update_cache: "yes"
    cache_valid_time: 3600

- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Install required security packages
  package:
    state: present
    name: "{{ item }}"
    update_cache: "yes"
    cache_valid_time: 3600
  with_items:
    - ufw
    - fail2ban
    - unattended-upgrades
    - logwatch

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny

- name: Allow ssh through firewall
  ufw:
    rule: allow
    name: OpenSSH
    state: enabled

- name: Allow localhost to communicate
  ufw:
    rule: allow
    src: 127.0.0.1
    state: enabled

- name: Allow outbound connections
  ufw:
    policy: allow
    direction: outgoing
    state: enabled

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd

- name: Create list of users allowed to ssh
  set_fact:
    allowed_ssh_users: "{{ allowed_ssh_users }} + [ '{{ item.name }}' ]"
  with_items: "{{ admin_users + standard_users }}"

- name: Restrict users allowed to ssh.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: 'AllowUsers {{ allowed_ssh_users | flatten | join(" ") }}'
    state: present
  notify: restart sshd

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart sshd
